### ISSUE TITLE
errors in windows

### ISSUE THREAD

**Issue by maknon** [Pato05/just_audio_media_kit#21]
Hi,

Im getting these errors in windows version:
```
package:media_kit_libs_windows_audio registered.
Debug service listening on ws://127.0.0.1:61298/GdMlX4ted4k=/ws
Syncing files to device Windows...
[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: MissingPluginException(No implementation found for method disposeAllPlayers on channel com.ryanheise.just_audio.methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      MethodChannelJustAudio.disposeAllPlayers (package:just_audio_platform_interface/method_channel_just_audio.dart:29:10)
<asynchronous suspension>

[ERROR:flutter/runtime/dart_vm_initializer.cc(40)] Unhandled Exception: MissingPluginException(No implementation found for method init on channel com.ryanheise.just_audio.methods)
#0      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:332:7)
<asynchronous suspension>
#1      MethodChannelJustAudio.init (package:just_audio_platform_interface/method_channel_just_audio.dart:13:5)
<asynchronous suspension>
#2      AudioPlayer._setPlatformActive.setPlatform (package:just_audio/just_audio.dart:1401:13)
<asynchronous suspension>
```
any hint on how to solve this

**Comment by Pato05** [comment]
Have you initialized the player with `JustAudioMediaKit.ensureInitialized`?

**Comment by maknon** [comment]
thanks, it works now.

the documentation is saying by default, windows and linux are enabled so maybe this needs to be updated

**Comment by Pato05** [comment]
> the documentation is saying by default, windows and linux are enabled so maybe this needs to be updated

It says that the `windows` and `linux` parameters are enabled (`true`) by default, but you still need to call the function, as it's necessary to register the plugin.
